esphome:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy
  name_add_mac_suffix: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Fallback AP mode
  ap:
    ssid: "BLE-Proxy Fallback"
    password: !secret ap_password

# API configuration is required for bluetooth_proxy
api:
  encryption:
    key: !secret api_encryption_key

logger:
  level: INFO  # 减少日志级别以节省空间

ota:
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot