esphome:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy
  name_add_mac_suffix: true

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

wifi:
  ssid: "ChinaMobile-WYF"
  password: "wsh.hxy.wyf"
  
  # Fallback AP mode
  ap:
    ssid: "BLE-Proxy Fallback"
    password: "12345678"

api:
  encryption:
    key: "RCgw9sagfQeWH19dfchHNpRtsvhGWSCgroxJ52fXJ58="

logger:
  level: INFO  # 减少日志级别以节省空间

ota:
  password: "12345678"

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot